const colors = {
  light: {
    text: '#0F172A',
    tint: '#3B5BDB',
    background: '#F8FAFC',
    foreground: '#0F172A',
    card: '#FFFFFF',
    cardForeground: '#0F172A',
    primary: '#3B5BDB',
    primaryForeground: '#FFFFFF',
    secondary: '#F1F5F9',
    secondaryForeground: '#1E293B',
    muted: '#F1F5F9',
    mutedForeground: '#64748B',
    accent: '#EFF6FF',
    accentForeground: '#1E40AF',
    destructive: '#DC2626',
    destructiveForeground: '#FFFFFF',
    border: '#E2E8F0',
    input: '#E2E8F0',
    success: '#16A34A',
    successSoft: '#F0FDF4',
    successForeground: '#FFFFFF',
    warning: '#D97706',
    warningSoft: '#FFFBEB',
    warningForeground: '#92400E',
    danger: '#DC2626',
    dangerSoft: '#FEF2F2',
    dangerForeground: '#FFFFFF',
    info: '#2563EB',
    infoSoft: '#EFF6FF',
    infoForeground: '#FFFFFF',
  },
  radius: 12,
};

export default colors;
